MELON_SETNAMES = [
 "Arabian Nights",
 "Collector's Edition",
 "International Collector's Edition",
 "Dragon Con",
 "Antiquities",
 "Legends",
 "The Dark",
 "Media Inserts",
 "Fallen Empires",
 "Legend Membership",
 "Ice Age",
 "Chronicles",
 "Homelands",
 "Alliances",
 "Rivals Quick Start Set",
 "Arena League",
 "Celebration",
 "Mirage",
 "Multiverse Gift Box",
 "Introductory Two-Player Set",
 "Visions",
 "Portal Demo Game",
 "Portal",
 "Vanguard",
 "Weatherlight",
 "Prerelease Events",
 "Tempest",
 "Stronghold",
 "Portal Second Age",
 "Judge Gift Program",
 "Exodus",
 "Unglued",
 "Asia Pacific Land Program",
 "Urza's Saga",
 "Anthologies",
 "Urza's Legacy",
 "Portal Three Kingdoms",
 "Urza's Destiny",
 "Starter 1999",
 "Guru",
 "Worlds",
 "Wizards of the Coast Online Store",
 "Mercadian Masques",
 "Super Series",
 "Friday Night Magic",
 "European Land Program",
 "Nemesis",
 "Starter 2000",
 "Prophecy",
 "Invasion",
 "Planeshift",
 "Unlimited",
 "Revised",
 "Beatdown",
 "Battle Royale",
 "4th Edition",
 "5th Edition",
 "6th Edition",
 "7th Edition",
 "Beta",
 "Magic Player Rewards",
 "Apocalypse",
 "Odyssey",
 "Deckmasters",
 "Torment",
 "Judgment",
 "Onslaught",
 "Legions",
 "Scourge",
 "Release Events",
 "Mirrodin",
 "Darksteel",
 "Fifth Dawn",
 "Champions of Kamigawa",
 "Unhinged",
 "Betrayers of Kamigawa",
 "Saviors of Kamigawa",
 "Two-Headed Giant Tournament",
 "Gateway",
 "Guildpact",
 "Champs and States",
 "Dissension",
 "Coldsnap",
 "Coldsnap Theme Decks",
 "Time Spiral",
 "Happy Holidays",
 "Planar Chaos",
 "Pro Tour",
 "Grand Prix",
 "Future Sight",
 "Magic Game Day",
 "Masters Edition",
 "Lorwyn",
 "Duel Decks: Elves vs. Goblins",
 "Launch Parties",
 "Morningtide",
 "15th Anniversary",
 "Shadowmoor",
 "Summer of Magic",
 "Eventide",
 "From the Vault: Dragons",
 "Masters Edition II",
 "Wizards Play Network",
 "Shards of Alara",
 "Duel Decks: Jace vs. Chandra",
 "Conflux",
 "Duel Decks: Divine vs. Demonic",
 "Alara Reborn",
 "From the Vault: Exiled",
 "Planechase",
 "Masters Edition III",
 "Zendikar",
 "Duel Decks: Garruk vs. Liliana",
 "Premium Deck Series: Slivers",
 "Worldwake",
 "8th Edition",
 "9th Edition",
 "10th Edition",
 "Magic Core Set 2010",
 "Ravnica",
 "Duel Decks: Phyrexia vs. the Coalition",
 "Rise of the Eldrazi",
 "Duels of the Planeswalkers",
 "Archenemy",
 "From the Vault: Relics",
 "Duel Decks: Elspeth vs. Tezzeret",
 "Scars of Mirrodin",
 "Premium Deck Series: Fire and Lightning",
 "Masters Edition IV",
 "Mirrodin Besieged",
 "Duel Decks: Knights vs. Dragons",
 "New Phyrexia",
 "From the Vault: Legends",
 "Duel Decks: Ajani vs. Nicol Bolas",
 "Innistrad",
 "Premium Deck Series: Graveborn",
 "Dark Ascension",
 "Duel Decks: Venser vs. Koth",
 "Avacyn Restored",
 "Planechase 2012 Edition",
 "From the Vault: Realms",
 "Duel Decks: Izzet vs. Golgari",
 "Return to Ravnica",
 "Commander's Arsenal",
 "Gatecrash",
 "Duel Decks: Sorin vs. Tibalt",
 "World Magic Cup Qualifiers",
 "Dragon's Maze",
 "Modern Masters",
 "From the Vault: Twenty",
 "Duel Decks: Heroes vs. Monsters",
 "Theros",
 "Born of the Gods",
 "Duel Decks: Jace vs. Vraska",
 "Journey into Nyx",
 "Modern Event Deck 2014",
 "Vintage Masters",
 "Clash Pack",
 "Duel Decks: Speed vs. Cunning",
 "Khans of Tarkir",
 "Commander 2014",
 "Duel Decks Anthology, Divine vs. Demonic",
 "Duel Decks Anthology, Elves vs. Goblins",
 "Duel Decks Anthology, Garruk vs. Liliana",
 "Commander 2013",
 "Magic Core Set 2011",
 "Magic Core Set 2012",
 "Magic Core Set 2013",
 "Magic Core Set 2014",
 "Magic Core Set 2015",
 "Conspiracy",
 "From the Vault: Annihilation",
 "Duel Decks Anthology, Jace vs. Chandra",
 "Ugin's Fate promos",
 "Fate Reforged",
 "Duel Decks: Elspeth vs. Kiora",
 "Dragons of Tarkir",
 "Tempest Remastered",
 "Magic Origins",
 "From the Vault: Angels",
 "Duel Decks: Zendikar vs. Eldrazi",
 "Battle for Zendikar",
 "Zendikar Expeditions",
 "Commander 2015",
 "Oath of the Gatewatch",
 "Commander",
 "Modern Masters 2015",
 "Alpha",
 "Time Spiral Timeshifted"
 ]