TCGPLAYER_SETS = [
"Oath of the Gatewatch",
"Battle for Zendikar",
"Dragons of Tarkir",
"Fate Reforged",
"Khans of Tarkir",
"Journey into Nyx",
"Born of the Gods",
"Theros",
"Dragon's Maze",
"Gatecrash",
"Return to Ravnica",
"Avacyn Restored",
"Dark Ascension",
"Innistrad",
"New Phyrexia",
"Mirrodin Besieged",
"Scars of Mirrodin",
"Rise of the Eldrazi",
"Worldwake",
"Zendikar",
"Alara Reborn",
"Conflux",
"Shards of Alara",
"Eventide",
"Shadowmoor",
"Morningtide",
"Lorwyn",
"Future Sight",
"Planar Chaos",
"Timeshifted",
"Time Spiral",
"Coldsnap",
"Dissension",
"Guildpact",
"Ravnica",
"Saviors of Kamigawa",
"Betrayers of Kamigawa",
"Champions of Kamigawa",
"Fifth Dawn",
"Darksteel",
"Mirrodin",
"Scourge",
"Legions",
"Onslaught",
"Judgment",
"Torment",
"Odyssey",
"Apocalypse",
"Planeshift",
"Invasion",
"Prophecy",
"Nemesis",
"Mercadian Masques",
"Urza's Destiny",
"Urza's Legacy",
"Urza's Saga",
"Exodus",
"Stronghold",
"Tempest",
"Weatherlight",
"Visions",
"Mirage",
"Alliances",
"Homelands",
"Ice Age",
"Fallen Empires",
"The Dark",
"Legends",
"Antiquities",
"Arabian Nights",
"Magic Origins",
"Magic 2015 (M15)",
"Magic 2014 (M14)",
"Magic 2013 (M13)",
"Magic 2012 (M12)",
"Magic 2011 (M11)",
"Magic 2010 (M10)",
"Tenth Edition",
"Ninth Edition",
"Eighth Edition",
"Seventh Edition",
"Sixth Edition",
"Fifth Edition",
"Fourth Edition",
"Revised Edition",
"Unlimited Edition",
"Beta Edition",
"Alpha Edition",
"Commander 2015",
"Modern Masters 2015",
"From the Vault: Annihilation",
"Conspiracy",
"Modern Masters",
"From the Vault: Angels",
"From the Vault: Dragons",
"From the Vault: Exiled",
"From the Vault: Legends",
"From the Vault: Realms",
"From the Vault: Relics",
"From the Vault: Twenty",
"Magic Modern Event Deck",
"Blessed vs. Cursed",
"Zendikar vs. Eldrazi",
"Elspeth vs. Kiora",
"Anthology",
"Speed vs. Cunning",
"Ajani vs. Nicol Bolas",
"Divine vs. Demonic",
"Elspeth vs. Tezzeret",
"Elves vs. Goblins",
"Garruk vs. Liliana",
"Heroes vs. Monsters",
"Izzet vs. Golgari",
"Jace vs. Chandra",
"Jace vs. Vraska",
"Knights vs. Dragons",
"Phyrexia vs. The Coalition",
"Sorin vs. Tibalt",
"Venser vs. Koth",
"PDS: Graveborn",
"PDS: Fire and Lightning",
"PDS: Slivers",
"Starter 1999",
"Starter 2000",
"Portal",
"Portal Second Age",
"Portal Three Kingdoms",
"Archenemy",
"Battle Royale Box Set",
"Beatdown Box Set",
"Chronicles",
"Commander",
"Commander 2013",
"Commander 2014",
"Commander's Arsenal",
"Planechase",
"Planechase 2012",
"Unglued",
"Unhinged",
"Vanguard",
"Zendikar Expeditions",
"Ugin's Fate Promos",
"APAC Lands",
"Arena Promos",
"Champs Promos",
"European Lands",
"FNM Promos",
"Game Day Promos",
"Gateway Promos",
"Grand Prix Promos",
"Guru Lands",
"JSS/MSS Promos",
"Judge Promos",
"Launch Party Cards",
"Magic Player Rewards",
"Media Promos",
"Prerelease Cards",
"Pro Tour Promos",
"Release Event Cards",
"Special Occasion",
"WPN Promos",
"Collector's Edition"
]